from pynput.keyboard import Key,Controller

#command list for msword
mswordcommandset = [['save'],['select','all'],['write'],['read'],['bold'],
['italic'],['underline'],['centre','text'],['open','file'],
['copy'],['paste'],['close','file'],['decrease','font','size'],
['cut','text'],['deselect'],['remove','bold'],['remove','italic'],
['remove','underline'],['increase','font','size'],['type'],['undo'],['redo'],
['left','align','text'],['right','align','text'],['create','new','document'],
['split','document','window'],['remove','split','document','window'],
['print','document'],['double','underline'],['remove','double','underline'],
['apply','subscript'],['remove','subscript'],['apply','superscript'],
['remove','superscript'],['one','character','right'],['one','character','left'],
['one','word','left'],['one','word','right'],['one','paragraph','up'],
['one','paragraph','down'],['one','line','up'],['one','line','down'],
['go','to','end','of','line'],['go','to','beginning','of','line'],
['go','to','end','of','document'],['go','to','beginning','of','document'],
['delete','one','left','character'],['delete','one','right','character'],
['delete','one','left','word'],['delete','one','right','word'],
['close','msword'],['new','line'],['caps','lock'],['padho'],['likho'],
['msword','band','karo'],['save','karo'],['pura','select','karo'],['deselect','karo'],
['file','kholo'],['text','center','kare'],['file','band','karo'],
['font','size','badhao'],['font','size','ghatao'],['text','cut','karo'],
['text','left','kare'],['text','right','kare'],['nayi','rekha'],
['print','karo']]

mswordcommandsdict ={'save':[Key.ctrl,'s'],'save karo':[Key.ctrl,'s'],
'select all': [Key.ctrl,'a'],'pura select karo': [Key.ctrl,'a'],
'deselect' : [Key.right,],'deselect karo' : [Key.right,],
'bold': [Key.ctrl,'b'],'italic': [Key.ctrl,'i'],'underline': [Key.ctrl,'u'],
'center text':[Key.ctrl,'e'],'text center kare':[Key.ctrl,'e'],'open file':[Key.ctrl,'o'],
'file kholo':[Key.ctrl,'o'],'copy':[Key.ctrl,'c'],
'paste':[Key.ctrl,'v'],'close file':[Key.ctrl,'w'],
'file band karo':[Key.ctrl,'w'],'decrease font size':[Key.ctrl,'['],
'font size ghatao':[Key.ctrl,'['],'font size badhao':[Key.ctrl,']'],
'increase font size':[Key.ctrl,']'],'cut text':[Key.ctrl,'x'],
'text cut karo':[Key.ctrl,'x'],'undo':[Key.ctrl,'z'],
'redo':[Key.ctrl,'y'],'left align text':[Key.ctrl,'l'],'text left karo':[Key.ctrl,'l'],
'text right karo':[Key.ctrl,'r'],'right align text':[Key.ctrl,'r'],
'create new document':[Key.ctrl,'n'],'split document window':[Key.ctrl,Key.alt,'s'],
'print document':[Key.ctrl,'p'],'print karo':[Key.ctrl,'p'],'double underline':[Key.ctrl,Key.shift,'d'],
'subscript':[Key.ctrl,'='],'superscript':[Key.ctrl,Key.shift,'='],
'one char left':[Key.left],'one char right':[Key.right],'one word left':[Key.ctrl,Key.left],
'one word right':[Key.ctrl,Key.right],'one para up':[Key.ctrl,Key.up],
'one para down':[Key.ctrl,Key.down],'one line up':[Key.up],'one line down':[Key.down],
'end of line':[Key.end],'beg of line':[Key.home],'end of document':[Key.ctrl,Key.end],
'beg of document':[Key.ctrl,Key.home],'delete one char left':[Key.backspace],
'delete one char right':[Key.delete],'delete one word left':[Key.ctrl,Key.backspace],
'delete one word right':[Key.ctrl,Key.delete],'new line':[Key.enter],'nayi rekha':[Key.enter],
'caps lock':[Key.caps_lock]
}
